// clang-format off
#include "settings/ui/facade/UserSettingsCoreStoreBridgeEntriesUi.inc"
#include "settings/ui/facade/UserSettingsCoreStoreBridgeEntriesDesktop.inc"
#include "settings/ui/facade/UserSettingsCoreStoreBridgeEntriesNavigation.inc"
#include "settings/ui/facade/UserSettingsCoreStoreBridgeEntriesNetwork.inc"
#include "settings/ui/facade/UserSettingsCoreStoreBridgeEntriesIntegrations.inc"
#include "settings/ui/facade/UserSettingsCoreStoreBridgeEntriesComposer.inc"
#include "settings/ui/facade/UserSettingsCoreStoreBridgeEntriesCalls.inc"
#include "settings/ui/facade/UserSettingsCoreStoreBridgeEntriesTimeline.inc"
#include "settings/ui/facade/UserSettingsCoreStoreBridgeEntriesEncryption.inc"
// clang-format on
