X(DesktopSystemTrayEnabled, settings.desktopSystemTrayEnabled())
X(DesktopSystemTrayAutostart, settings.desktopSystemTrayAutostart())
X(DesktopNotificationsEnabled, settings.desktopNotificationsEnabled())
X(DesktopNotificationsAttentionOnIncoming, settings.desktopNotificationsAttentionOnIncoming())
X(DesktopNotificationsMessageContentPolicy,
  static_cast<int>(settings.desktopNotificationsMessageContentPolicy()))
X(DesktopWindowFocusBlurEnabled, settings.desktopWindowFocusBlurEnabled())
X(DesktopWindowFocusBlurDelaySeconds, settings.desktopWindowFocusBlurDelaySeconds())
