// SPDX-FileCopyrightText: Nheko Contributors
// SPDX-FileCopyrightText: Komai Contributors
//
// SPDX-License-Identifier: GPL-3.0-or-later

static QVariant
encryptionOnlineBackupKeyStatusValue()
{
    return false;
}

static QVariant
encryptionSelfSigningKeyStatusValue()
{
    return false;
}

static QVariant
encryptionUserSigningKeyStatusValue()
{
    return false;
}

static QVariant
encryptionMasterSigningKeyStatusValue()
{
    return false;
}
