// SPDX-FileCopyrightText: Nheko Contributors
// SPDX-FileCopyrightText: Komai Contributors
//
// SPDX-License-Identifier: GPL-3.0-or-later

#include "settings/ui/SettingDescriptorCallbacksCommon.inc"
#include "settings/ui/SettingDescriptorCallbacksLookFeel.inc"
#include "settings/ui/SettingDescriptorCallbacksIntegrations.inc"
#include "settings/ui/SettingDescriptorCallbacksNetwork.inc"
#include "settings/ui/SettingDescriptorCallbacksPrivacy.inc"
#include "settings/ui/SettingDescriptorCallbacksCalls.inc"
#include "settings/ui/SettingDescriptorCallbacksOptionsSidebars.inc"
#include "settings/ui/SettingDescriptorCallbacksOptionsTimeline.inc"
#include "settings/ui/SettingDescriptorCallbacksOptionsComposer.inc"
#include "settings/ui/SettingDescriptorCallbacksOptionsNotifications.inc"
#include "settings/ui/SettingDescriptorCallbacksReadOnlyEncryption.inc"
#include "settings/ui/SettingDescriptorCallbacksReadOnlyAccount.inc"
#include "settings/ui/SettingDescriptorCallbacksReadOnlyAbout.inc"
