// SPDX-FileCopyrightText: Nheko Contributors
// SPDX-FileCopyrightText: Komai Contributors
//
// SPDX-License-Identifier: GPL-3.0-or-later

#include "settings/ui/SettingDescriptorCallbacksCommon.inc"
#include "settings/ui/SettingDescriptorCallbacksLookFeel.inc"
#include "settings/ui/SettingDescriptorCallbacksIntegrationsPrivacy.inc"
#include "settings/ui/SettingDescriptorCallbacksCalls.inc"
#include "settings/ui/SettingDescriptorCallbacksOptions.inc"
#include "settings/ui/SettingDescriptorCallbacksReadOnly.inc"
