// Auto-generated by bin/generate-themes.py — DO NOT EDIT
// Re-generate with: python3 bin/generate-themes.py <output>

#pragma once

#include <QColor>
#include <QPalette>
#include <QString>
#include <QStringList>
#include <vector>

struct ThemeDef {
    QString slug;
    QString name;
    QString variant;  // "light" or "dark"
    int sortOrder;

    // QPalette colors
    QColor window, windowText, base, alternateBase, text, brightText;
    QColor button, buttonText, light, mid, dark;
    QColor highlight, highlightedText, link;
    QColor toolTipBase, toolTipText;

    // Custom Theme properties
    QColor red, green, orange, error;

    QPalette toPalette() const {
        QPalette p(windowText, button, light, dark, mid, text, brightText, base, window);
        p.setColor(QPalette::AlternateBase, alternateBase);
        p.setColor(QPalette::Highlight, highlight);
        p.setColor(QPalette::HighlightedText, highlightedText);
        p.setColor(QPalette::ToolTipBase, toolTipBase);
        p.setColor(QPalette::ToolTipText, toolTipText);
        p.setColor(QPalette::Link, link);
        p.setColor(QPalette::ButtonText, buttonText);
        return p;
    }
};

inline const std::vector<ThemeDef>& themeDefinitions() {
    static const std::vector<ThemeDef> themes = {
        ThemeDef{
            QStringLiteral("komai"),
            QStringLiteral("Komai"),
            QStringLiteral("light"),
            0,
            // QPalette colors
            /*window*/ QColor(0xff, 0xff, 0xff),
            /*windowText*/ QColor(0x33, 0x42, 0x58),
            /*base*/ QColor(0xff, 0xff, 0xff),
            /*alternateBase*/ QColor(0xee, 0xee, 0xee),
            /*text*/ QColor(0x33, 0x42, 0x58),
            /*brightText*/ QColor(0xf2, 0xf5, 0xf8),
            /*button*/ QColor(0xff, 0xff, 0xff),
            /*buttonText*/ QColor(0x55, 0x54, 0x59),
            /*light*/ QColor(0xef, 0xef, 0xef),
            /*mid*/ QColor(0xdc, 0xdc, 0xdc),
            /*dark*/ QColor(0x33, 0x42, 0x58),
            /*highlight*/ QColor(0xf4, 0x93, 0x00),
            /*highlightedText*/ QColor(0xff, 0xff, 0xff),
            /*link*/ QColor(0xb5, 0x6e, 0x00),
            /*toolTipBase*/ QColor(0xff, 0xff, 0xff),
            /*toolTipText*/ QColor(0x33, 0x42, 0x58),
            // Custom properties
            /*red*/ QColor(0xa8, 0x23, 0x53),
            /*green*/ QColor(0x00, 0x80, 0x00),
            /*orange*/ QColor(0xf4, 0x93, 0x00),
            /*error*/ QColor(0xdd, 0x3d, 0x3d),
        },
        ThemeDef{
            QStringLiteral("komai-dark"),
            QStringLiteral("Komai Dark"),
            QStringLiteral("dark"),
            1,
            // QPalette colors
            /*window*/ QColor(0x29, 0x2a, 0x2b),
            /*windowText*/ QColor(0xca, 0xcc, 0xd1),
            /*base*/ QColor(0x06, 0x16, 0x21),
            /*alternateBase*/ QColor(0x29, 0x2a, 0x2b),
            /*text*/ QColor(0xca, 0xcc, 0xd1),
            /*brightText*/ QColor(0xf4, 0xf5, 0xf8),
            /*button*/ QColor(0xff, 0xff, 0xff),
            /*buttonText*/ QColor(0x82, 0x82, 0x84),
            /*light*/ QColor(0xca, 0xcc, 0xd1),
            /*mid*/ QColor(0x20, 0x22, 0x28),
            /*dark*/ QColor(0x06, 0x16, 0x21),
            /*highlight*/ QColor(0xf4, 0x93, 0x00),
            /*highlightedText*/ QColor(0xff, 0xff, 0xff),
            /*link*/ QColor(0xff, 0xc0, 0x60),
            /*toolTipBase*/ QColor(0x06, 0x16, 0x21),
            /*toolTipText*/ QColor(0xca, 0xcc, 0xd1),
            // Custom properties
            /*red*/ QColor(0xa8, 0x23, 0x53),
            /*green*/ QColor(0x00, 0x80, 0x00),
            /*orange*/ QColor(0xff, 0xc0, 0x60),
            /*error*/ QColor(0xdd, 0x3d, 0x3d),
        },
        ThemeDef{
            QStringLiteral("breeze-dark"),
            QStringLiteral("Breeze Dark"),
            QStringLiteral("dark"),
            200,
            // QPalette colors
            /*window*/ QColor(0x2a, 0x2e, 0x32),
            /*windowText*/ QColor(0xfc, 0xfc, 0xfc),
            /*base*/ QColor(0x23, 0x26, 0x29),
            /*alternateBase*/ QColor(0x2a, 0x2e, 0x32),
            /*text*/ QColor(0xfc, 0xfc, 0xfc),
            /*brightText*/ QColor(0xff, 0xff, 0xff),
            /*button*/ QColor(0x31, 0x36, 0x3b),
            /*buttonText*/ QColor(0xa1, 0xa9, 0xb1),
            /*light*/ QColor(0xef, 0xf0, 0xf1),
            /*mid*/ QColor(0x31, 0x36, 0x3b),
            /*dark*/ QColor(0x23, 0x26, 0x29),
            /*highlight*/ QColor(0x3d, 0xae, 0xe9),
            /*highlightedText*/ QColor(0xfc, 0xfc, 0xfc),
            /*link*/ QColor(0x1d, 0x99, 0xf3),
            /*toolTipBase*/ QColor(0x23, 0x26, 0x29),
            /*toolTipText*/ QColor(0xfc, 0xfc, 0xfc),
            // Custom properties
            /*red*/ QColor(0xda, 0x44, 0x53),
            /*green*/ QColor(0x27, 0xae, 0x60),
            /*orange*/ QColor(0xf6, 0x74, 0x00),
            /*error*/ QColor(0xda, 0x44, 0x53),
        },
        ThemeDef{
            QStringLiteral("catppuccin-latte"),
            QStringLiteral("Catppuccin Latte"),
            QStringLiteral("light"),
            200,
            // QPalette colors
            /*window*/ QColor(0xef, 0xf1, 0xf5),
            /*windowText*/ QColor(0x4c, 0x4f, 0x69),
            /*base*/ QColor(0xcc, 0xd0, 0xda),
            /*alternateBase*/ QColor(0xbc, 0xc0, 0xcc),
            /*text*/ QColor(0x4c, 0x4f, 0x69),
            /*brightText*/ QColor(0x72, 0x87, 0xfd),
            /*button*/ QColor(0xcc, 0xd0, 0xda),
            /*buttonText*/ QColor(0x6c, 0x6f, 0x85),
            /*light*/ QColor(0xdc, 0x8a, 0x78),
            /*mid*/ QColor(0x9c, 0xa0, 0xb0),
            /*dark*/ QColor(0xcc, 0xd0, 0xda),
            /*highlight*/ QColor(0x1e, 0x66, 0xf5),
            /*highlightedText*/ QColor(0xef, 0xf1, 0xf5),
            /*link*/ QColor(0x1e, 0x66, 0xf5),
            /*toolTipBase*/ QColor(0xcc, 0xd0, 0xda),
            /*toolTipText*/ QColor(0x4c, 0x4f, 0x69),
            // Custom properties
            /*red*/ QColor(0xd2, 0x0f, 0x39),
            /*green*/ QColor(0x40, 0xa0, 0x2b),
            /*orange*/ QColor(0xfe, 0x64, 0x0b),
            /*error*/ QColor(0xd2, 0x0f, 0x39),
        },
        ThemeDef{
            QStringLiteral("catppuccin-mocha"),
            QStringLiteral("Catppuccin Mocha"),
            QStringLiteral("dark"),
            200,
            // QPalette colors
            /*window*/ QColor(0x1e, 0x1e, 0x2e),
            /*windowText*/ QColor(0xcd, 0xd6, 0xf4),
            /*base*/ QColor(0x31, 0x32, 0x44),
            /*alternateBase*/ QColor(0x45, 0x47, 0x5a),
            /*text*/ QColor(0xcd, 0xd6, 0xf4),
            /*brightText*/ QColor(0xb4, 0xbe, 0xfe),
            /*button*/ QColor(0x31, 0x32, 0x44),
            /*buttonText*/ QColor(0xa6, 0xad, 0xc8),
            /*light*/ QColor(0xf5, 0xe0, 0xdc),
            /*mid*/ QColor(0x6c, 0x70, 0x86),
            /*dark*/ QColor(0x31, 0x32, 0x44),
            /*highlight*/ QColor(0x89, 0xb4, 0xfa),
            /*highlightedText*/ QColor(0xb4, 0xbe, 0xfe),
            /*link*/ QColor(0x89, 0xb4, 0xfa),
            /*toolTipBase*/ QColor(0x31, 0x32, 0x44),
            /*toolTipText*/ QColor(0xcd, 0xd6, 0xf4),
            // Custom properties
            /*red*/ QColor(0xf3, 0x8b, 0xa8),
            /*green*/ QColor(0xa6, 0xe3, 0xa1),
            /*orange*/ QColor(0xfa, 0xb3, 0x87),
            /*error*/ QColor(0xf3, 0x8b, 0xa8),
        },
        ThemeDef{
            QStringLiteral("dracula"),
            QStringLiteral("Dracula"),
            QStringLiteral("dark"),
            200,
            // QPalette colors
            /*window*/ QColor(0x28, 0x2a, 0x36),
            /*windowText*/ QColor(0xf8, 0xf8, 0xf2),
            /*base*/ QColor(0x36, 0x34, 0x47),
            /*alternateBase*/ QColor(0x44, 0x47, 0x5a),
            /*text*/ QColor(0xf8, 0xf8, 0xf2),
            /*brightText*/ QColor(0xff, 0xff, 0xff),
            /*button*/ QColor(0x36, 0x34, 0x47),
            /*buttonText*/ QColor(0x9e, 0xa8, 0xc7),
            /*light*/ QColor(0xf0, 0xf1, 0xf4),
            /*mid*/ QColor(0x62, 0x72, 0xa4),
            /*dark*/ QColor(0x36, 0x34, 0x47),
            /*highlight*/ QColor(0x80, 0xbf, 0xff),
            /*highlightedText*/ QColor(0xff, 0xff, 0xff),
            /*link*/ QColor(0x80, 0xbf, 0xff),
            /*toolTipBase*/ QColor(0x36, 0x34, 0x47),
            /*toolTipText*/ QColor(0xf8, 0xf8, 0xf2),
            // Custom properties
            /*red*/ QColor(0xff, 0x55, 0x55),
            /*green*/ QColor(0x50, 0xfa, 0x7b),
            /*orange*/ QColor(0xff, 0xb8, 0x6c),
            /*error*/ QColor(0xff, 0x55, 0x55),
        },
        ThemeDef{
            QStringLiteral("gruvbox-dark"),
            QStringLiteral("Gruvbox Dark"),
            QStringLiteral("dark"),
            200,
            // QPalette colors
            /*window*/ QColor(0x28, 0x28, 0x28),
            /*windowText*/ QColor(0xd5, 0xc4, 0xa1),
            /*base*/ QColor(0x3c, 0x38, 0x36),
            /*alternateBase*/ QColor(0x50, 0x49, 0x45),
            /*text*/ QColor(0xd5, 0xc4, 0xa1),
            /*brightText*/ QColor(0xfb, 0xf1, 0xc7),
            /*button*/ QColor(0x3c, 0x38, 0x36),
            /*buttonText*/ QColor(0xbd, 0xae, 0x93),
            /*light*/ QColor(0xeb, 0xdb, 0xb2),
            /*mid*/ QColor(0x66, 0x5c, 0x54),
            /*dark*/ QColor(0x3c, 0x38, 0x36),
            /*highlight*/ QColor(0x83, 0xa5, 0x98),
            /*highlightedText*/ QColor(0xfb, 0xf1, 0xc7),
            /*link*/ QColor(0x83, 0xa5, 0x98),
            /*toolTipBase*/ QColor(0x3c, 0x38, 0x36),
            /*toolTipText*/ QColor(0xd5, 0xc4, 0xa1),
            // Custom properties
            /*red*/ QColor(0xfb, 0x49, 0x34),
            /*green*/ QColor(0xb8, 0xbb, 0x26),
            /*orange*/ QColor(0xfe, 0x80, 0x19),
            /*error*/ QColor(0xfb, 0x49, 0x34),
        },
        ThemeDef{
            QStringLiteral("gruvbox-light"),
            QStringLiteral("Gruvbox Light"),
            QStringLiteral("light"),
            200,
            // QPalette colors
            /*window*/ QColor(0xfb, 0xf1, 0xc7),
            /*windowText*/ QColor(0x50, 0x49, 0x45),
            /*base*/ QColor(0xeb, 0xdb, 0xb2),
            /*alternateBase*/ QColor(0xd5, 0xc4, 0xa1),
            /*text*/ QColor(0x50, 0x49, 0x45),
            /*brightText*/ QColor(0x28, 0x28, 0x28),
            /*button*/ QColor(0xeb, 0xdb, 0xb2),
            /*buttonText*/ QColor(0x66, 0x5c, 0x54),
            /*light*/ QColor(0x3c, 0x38, 0x36),
            /*mid*/ QColor(0xbd, 0xae, 0x93),
            /*dark*/ QColor(0xeb, 0xdb, 0xb2),
            /*highlight*/ QColor(0x07, 0x66, 0x78),
            /*highlightedText*/ QColor(0xfb, 0xf1, 0xc7),
            /*link*/ QColor(0x07, 0x66, 0x78),
            /*toolTipBase*/ QColor(0xeb, 0xdb, 0xb2),
            /*toolTipText*/ QColor(0x50, 0x49, 0x45),
            // Custom properties
            /*red*/ QColor(0x9d, 0x00, 0x06),
            /*green*/ QColor(0x79, 0x74, 0x0e),
            /*orange*/ QColor(0xaf, 0x3a, 0x03),
            /*error*/ QColor(0x9d, 0x00, 0x06),
        },
        ThemeDef{
            QStringLiteral("nord"),
            QStringLiteral("Nord"),
            QStringLiteral("dark"),
            200,
            // QPalette colors
            /*window*/ QColor(0x2e, 0x34, 0x40),
            /*windowText*/ QColor(0xe5, 0xe9, 0xf0),
            /*base*/ QColor(0x3b, 0x42, 0x52),
            /*alternateBase*/ QColor(0x43, 0x4c, 0x5e),
            /*text*/ QColor(0xe5, 0xe9, 0xf0),
            /*brightText*/ QColor(0x8f, 0xbc, 0xbb),
            /*button*/ QColor(0x3b, 0x42, 0x52),
            /*buttonText*/ QColor(0xd8, 0xde, 0xe9),
            /*light*/ QColor(0xec, 0xef, 0xf4),
            /*mid*/ QColor(0x4c, 0x56, 0x6a),
            /*dark*/ QColor(0x3b, 0x42, 0x52),
            /*highlight*/ QColor(0x81, 0xa1, 0xc1),
            /*highlightedText*/ QColor(0x8f, 0xbc, 0xbb),
            /*link*/ QColor(0x81, 0xa1, 0xc1),
            /*toolTipBase*/ QColor(0x3b, 0x42, 0x52),
            /*toolTipText*/ QColor(0xe5, 0xe9, 0xf0),
            // Custom properties
            /*red*/ QColor(0xbf, 0x61, 0x6a),
            /*green*/ QColor(0xa3, 0xbe, 0x8c),
            /*orange*/ QColor(0xd0, 0x87, 0x70),
            /*error*/ QColor(0xbf, 0x61, 0x6a),
        },
        ThemeDef{
            QStringLiteral("solarized-dark"),
            QStringLiteral("Solarized Dark"),
            QStringLiteral("dark"),
            200,
            // QPalette colors
            /*window*/ QColor(0x00, 0x2b, 0x36),
            /*windowText*/ QColor(0x93, 0xa1, 0xa1),
            /*base*/ QColor(0x07, 0x36, 0x42),
            /*alternateBase*/ QColor(0x58, 0x6e, 0x75),
            /*text*/ QColor(0x93, 0xa1, 0xa1),
            /*brightText*/ QColor(0xfd, 0xf6, 0xe3),
            /*button*/ QColor(0x07, 0x36, 0x42),
            /*buttonText*/ QColor(0x83, 0x94, 0x96),
            /*light*/ QColor(0xee, 0xe8, 0xd5),
            /*mid*/ QColor(0x65, 0x7b, 0x83),
            /*dark*/ QColor(0x07, 0x36, 0x42),
            /*highlight*/ QColor(0x26, 0x8b, 0xd2),
            /*highlightedText*/ QColor(0xfd, 0xf6, 0xe3),
            /*link*/ QColor(0x26, 0x8b, 0xd2),
            /*toolTipBase*/ QColor(0x07, 0x36, 0x42),
            /*toolTipText*/ QColor(0x93, 0xa1, 0xa1),
            // Custom properties
            /*red*/ QColor(0xdc, 0x32, 0x2f),
            /*green*/ QColor(0x85, 0x99, 0x00),
            /*orange*/ QColor(0xcb, 0x4b, 0x16),
            /*error*/ QColor(0xdc, 0x32, 0x2f),
        },
        ThemeDef{
            QStringLiteral("solarized-light"),
            QStringLiteral("Solarized Light"),
            QStringLiteral("light"),
            200,
            // QPalette colors
            /*window*/ QColor(0xfd, 0xf6, 0xe3),
            /*windowText*/ QColor(0x58, 0x6e, 0x75),
            /*base*/ QColor(0xee, 0xe8, 0xd5),
            /*alternateBase*/ QColor(0x93, 0xa1, 0xa1),
            /*text*/ QColor(0x58, 0x6e, 0x75),
            /*brightText*/ QColor(0x00, 0x2b, 0x36),
            /*button*/ QColor(0xee, 0xe8, 0xd5),
            /*buttonText*/ QColor(0x65, 0x7b, 0x83),
            /*light*/ QColor(0x07, 0x36, 0x42),
            /*mid*/ QColor(0x83, 0x94, 0x96),
            /*dark*/ QColor(0xee, 0xe8, 0xd5),
            /*highlight*/ QColor(0x26, 0x8b, 0xd2),
            /*highlightedText*/ QColor(0xfd, 0xf6, 0xe3),
            /*link*/ QColor(0x26, 0x8b, 0xd2),
            /*toolTipBase*/ QColor(0xee, 0xe8, 0xd5),
            /*toolTipText*/ QColor(0x58, 0x6e, 0x75),
            // Custom properties
            /*red*/ QColor(0xdc, 0x32, 0x2f),
            /*green*/ QColor(0x85, 0x99, 0x00),
            /*orange*/ QColor(0xcb, 0x4b, 0x16),
            /*error*/ QColor(0xdc, 0x32, 0x2f),
        },
        ThemeDef{
            QStringLiteral("tokyo-night"),
            QStringLiteral("Tokyo Night"),
            QStringLiteral("dark"),
            200,
            // QPalette colors
            /*window*/ QColor(0x1a, 0x1b, 0x26),
            /*windowText*/ QColor(0xa9, 0xb1, 0xd6),
            /*base*/ QColor(0x16, 0x16, 0x1e),
            /*alternateBase*/ QColor(0x2f, 0x35, 0x49),
            /*text*/ QColor(0xa9, 0xb1, 0xd6),
            /*brightText*/ QColor(0xd5, 0xd6, 0xdb),
            /*button*/ QColor(0x16, 0x16, 0x1e),
            /*buttonText*/ QColor(0x78, 0x7c, 0x99),
            /*light*/ QColor(0xcb, 0xcc, 0xd1),
            /*mid*/ QColor(0x44, 0x4b, 0x6a),
            /*dark*/ QColor(0x16, 0x16, 0x1e),
            /*highlight*/ QColor(0x2a, 0xc3, 0xde),
            /*highlightedText*/ QColor(0xd5, 0xd6, 0xdb),
            /*link*/ QColor(0x2a, 0xc3, 0xde),
            /*toolTipBase*/ QColor(0x16, 0x16, 0x1e),
            /*toolTipText*/ QColor(0xa9, 0xb1, 0xd6),
            // Custom properties
            /*red*/ QColor(0xc0, 0xca, 0xf5),
            /*green*/ QColor(0x9e, 0xce, 0x6a),
            /*orange*/ QColor(0xa9, 0xb1, 0xd6),
            /*error*/ QColor(0xc0, 0xca, 0xf5),
        },
        ThemeDef{
            QStringLiteral("nheko-dark"),
            QStringLiteral("Nheko Dark"),
            QStringLiteral("dark"),
            207,
            // QPalette colors
            /*window*/ QColor(0x2d, 0x31, 0x39),
            /*windowText*/ QColor(0xca, 0xcc, 0xd1),
            /*base*/ QColor(0x20, 0x22, 0x28),
            /*alternateBase*/ QColor(0x2d, 0x31, 0x39),
            /*text*/ QColor(0xca, 0xcc, 0xd1),
            /*brightText*/ QColor(0xf4, 0xf5, 0xf8),
            /*button*/ QColor(0xff, 0xff, 0xff),
            /*buttonText*/ QColor(0x82, 0x82, 0x84),
            /*light*/ QColor(0xca, 0xcc, 0xd1),
            /*mid*/ QColor(0x20, 0x22, 0x28),
            /*dark*/ QColor(0x3c, 0x46, 0x4d),
            /*highlight*/ QColor(0x38, 0xa3, 0xd8),
            /*highlightedText*/ QColor(0xf4, 0xf5, 0xf8),
            /*link*/ QColor(0x38, 0xa3, 0xd8),
            /*toolTipBase*/ QColor(0x20, 0x22, 0x28),
            /*toolTipText*/ QColor(0xca, 0xcc, 0xd1),
            // Custom properties
            /*red*/ QColor(0xa8, 0x23, 0x53),
            /*green*/ QColor(0x00, 0x80, 0x00),
            /*orange*/ QColor(0xfc, 0xc5, 0x3a),
            /*error*/ QColor(0xdd, 0x3d, 0x3d),
        },
        ThemeDef{
            QStringLiteral("nheko-light"),
            QStringLiteral("Nheko Light"),
            QStringLiteral("light"),
            216,
            // QPalette colors
            /*window*/ QColor(0xff, 0xff, 0xff),
            /*windowText*/ QColor(0x33, 0x33, 0x33),
            /*base*/ QColor(0xff, 0xff, 0xff),
            /*alternateBase*/ QColor(0xee, 0xee, 0xee),
            /*text*/ QColor(0x33, 0x33, 0x33),
            /*brightText*/ QColor(0xf2, 0xf5, 0xf8),
            /*button*/ QColor(0xff, 0xff, 0xff),
            /*buttonText*/ QColor(0x55, 0x54, 0x59),
            /*light*/ QColor(0xef, 0xef, 0xef),
            /*mid*/ QColor(0xdc, 0xdc, 0xdc),
            /*dark*/ QColor(0x46, 0x4d, 0x5d),
            /*highlight*/ QColor(0x38, 0xa3, 0xd8),
            /*highlightedText*/ QColor(0xf4, 0xf4, 0xf5),
            /*link*/ QColor(0x00, 0x77, 0xb5),
            /*toolTipBase*/ QColor(0xff, 0xff, 0xff),
            /*toolTipText*/ QColor(0x33, 0x33, 0x33),
            // Custom properties
            /*red*/ QColor(0xa8, 0x23, 0x53),
            /*green*/ QColor(0x00, 0x80, 0x00),
            /*orange*/ QColor(0xfc, 0xbe, 0x05),
            /*error*/ QColor(0xdd, 0x3d, 0x3d),
        },
    };
    return themes;
}

inline const ThemeDef* findTheme(QStringView slug) {
    for (const auto& t : themeDefinitions()) {
        if (t.slug == slug) return &t;
    }
    return nullptr;
}

inline QStringList themeNames(const QString& variant = QString()) {
    QStringList names;
    for (const auto& t : themeDefinitions()) {
        if (variant.isEmpty() || t.variant == variant)
            names.append(t.name);
    }
    return names;
}

inline QStringList themeSlugs(const QString& variant = QString()) {
    QStringList slugs;
    for (const auto& t : themeDefinitions()) {
        if (variant.isEmpty() || t.variant == variant)
            slugs.append(t.slug);
    }
    return slugs;
}

inline QString themeVariant(QStringView slug) {
    if (slug == u"system") return QStringLiteral("system");
    const auto *def = findTheme(slug);
    return def ? def->variant : QStringLiteral("light");
}

inline QString defaultThemeSlug(QStringView variant) {
    if (variant == u"system") return QStringLiteral("system");
    for (const auto& t : themeDefinitions()) {
        if (t.variant == variant) return t.slug;
    }
    return QStringLiteral("komai");
}

