  // ui
  SettingId::UiScrollbarPolicy,
  SettingId::UiAvatarsDefaultAvatarStyle,

  // sidebars
  SettingId::SidebarsRoomListLastMessagePreview,
  SettingId::SidebarsRoomListSort,
  SettingId::SidebarsRoomListUnreadDetectionPolicy,

  // network
  SettingId::NetworkPresenceStatusPolicy,

  // integrations
  SettingId::IntegrationsDbusApiAccess,

  // composer
  SettingId::ComposerInputSendKey,
  SettingId::ComposerInputAutoReplaceEmoji,
  SettingId::ComposerInputEmojiPreferredGender,
  SettingId::ComposerInputEmojiPreferredSkinTone,

  // notifications
  SettingId::NotificationsMessageContentPolicy,

  // timeline
  SettingId::TimelineMessagesStyle,
  SettingId::TimelineMessagesPositioning,
  SettingId::TimelineUserColorCodingPolicy,
  SettingId::TimelineMessagesSenderUsername,
  SettingId::TimelineMessageActionsActivationPolicy,
  SettingId::TimelineMediaImageDisplay,
