  // timeline
  SettingId::TimelineMessagesLayoutMaxWidthPercent,
  SettingId::TimelineMessagesLayoutAdaptivePositioningBreakpointPx,

  // calls
  SettingId::CallsScreenshareFrameRate,
  // navigation
  SettingId::NavigationTabsPreferredWidthPx,
  SettingId::NavigationTabsMinimumWidthPx,
  SettingId::NavigationTabsMaxRecentlyClosedTimelines,

  // desktop
  SettingId::DesktopWindowFocusBlurDelaySeconds,
