  // sidebars
  SettingId::SidebarsRoomListLastMessagePreview,
  SettingId::SidebarsRoomListSort,

  // network
  SettingId::NetworkPresenceStatusPolicy,

  // integrations
  SettingId::IntegrationsDbusApiAccess,

  // composer
  SettingId::ComposerInputSendKey,
  SettingId::ComposerInputAutoReplaceEmoji,

  // notifications
  SettingId::NotificationsMessageContentPolicy,

  // timeline
  SettingId::TimelineMessagesLayoutStyle,
  SettingId::TimelineMessagesSenderUsername,
  SettingId::TimelineMessageActionsActivationPolicy,
  SettingId::TimelineMediaImageDisplay,
