    // Composer
    CONNECT_SETTING_ID(ComposerInputMarkdownToHtmlEnabled, composerInputMarkdownToHtmlEnabledChanged, Value);
    CONNECT_SETTING_ID(ComposerInputTranscriptionEnabled, composerInputTranscriptionEnabledChanged, Value);
    CONNECT_SETTING_ID(ComposerInputSendKey, composerInputSendKeyChanged, Value);
    CONNECT_SETTING_ID(ComposerInputAutoReplaceEmoji, composerInputAutoReplaceEmojiChanged, Value);
    CONNECT_SETTING_ID(ComposerInputEmojiPreferredGender, composerInputEmojiPreferredGenderChanged, Value);
    CONNECT_SETTING_ID(ComposerInputEmojiPreferredSkinTone, composerInputEmojiPreferredSkinToneChanged, Value);
    CONNECT_SETTING_ID(ComposerTypingSendEnabled, composerTypingSendEnabledChanged, Value);
