    // Timeline
    CONNECT_SETTING_ID(TimelineMessagesLayoutBubbles, timelineBubblesEnabledChanged, Value);
    CONNECT_SETTING_ID(
      TimelineMessagesLayoutSmallAvatars, timelineSmallAvatarsEnabledChanged, Value);
    CONNECT_SETTING_ID(
      TimelineMessagesLayoutShowOwnAvatar, timelineShowOwnAvatarInBubbleLayoutChanged, Value);
    CONNECT_SETTING_ID(TimelineMessagesSenderUsername, showSenderUsernameChanged, Value);
    CONNECT_SETTING_ID(TimelineMessagesMaxWidthPx, maxTimelineWidthChanged, Value);
    CONNECT_SETTING_ID(TimelineMessagesEmojiOnlyEnlarge, enlargeEmojiOnlyMessagesChanged, Value);
    CONNECT_SETTING_ID(TimelineMessagesHoverHighlight, messageHoverHighlightChanged, Value);
    CONNECT_SETTING_ID(TimelineMessageActionsEnabled, timelineMessageActionsEnabledChanged, Value);
    CONNECT_SETTING_ID(TimelineMessageActionsPinnedReactions, pinnedReactionsChanged, Value);
    CONNECT_SETTING_ID(TimelineMediaEffectsEnabled, timelineMediaEffectsEnabledChanged, Value);
    CONNECT_SETTING_ID(TimelineMediaAnimateOnHover, animateImagesOnHoverChanged, Value);
    CONNECT_SETTING_ID(TimelineMediaImageDisplay, showImageChanged, Value);
    CONNECT_SETTING_ID(TimelineMediaOpenImagesExternal, openImagesInExternalAppChanged, Value);
    CONNECT_SETTING_ID(TimelineMediaOpenVideosExternal, openVideosInExternalAppChanged, Value);
