    // Timeline
    CONNECT_SETTING(Bubbles, bubblesChanged, Value);
    CONNECT_SETTING(SmallAvatars, smallAvatarsChanged, Value);
    CONNECT_SETTING(ShowOwnAvatarInBubbleLayout, showOwnAvatarInBubbleLayoutChanged, Value);
    CONNECT_SETTING(ShowSenderUsername, showSenderUsernameChanged, Value);
    CONNECT_SETTING(MaxTimelineWidth, maxTimelineWidthChanged, Value);
    CONNECT_SETTING(EnlargeEmojiOnlyMessages, enlargeEmojiOnlyMessagesChanged, Value);
    CONNECT_SETTING(MessageHoverHighlight, messageHoverHighlightChanged, Value);
    CONNECT_SETTING(ShowActionButtons, showActionButtonsChanged, Value);
    CONNECT_SETTING(PinnedReactions, pinnedReactionsChanged, Value);
    CONNECT_SETTING(FancyEffects, fancyEffectsChanged, Value);
    CONNECT_SETTING(AnimateImagesOnHover, animateImagesOnHoverChanged, Value);
    CONNECT_SETTING(ShowImage, showImageChanged, Value);
    CONNECT_SETTING(OpenImagesInExternalApp, openImagesInExternalAppChanged, Value);
    CONNECT_SETTING(OpenVideosInExternalApp, openVideosInExternalAppChanged, Value);
