    // Composer
    CONNECT_SETTING_ID(ComposerInputMarkdownEnabled, markdownChanged, Value);
    CONNECT_SETTING_ID(ComposerInputSendKey, sendMessageKeyChanged, Value);
    CONNECT_SETTING_ID(ComposerInputAutoReplaceEmoji, autoReplaceEmojiChanged, Value);
    CONNECT_SETTING_ID(ComposerFeedbackTypingNotifications, typingNotificationsChanged, Value);
    CONNECT_SETTING_ID(ComposerFeedbackReadReceipts, readReceiptsChanged, Value);
    CONNECT_SETTING_ID(ComposerExtrasStickersEnabled, enableStickersChanged, Value);
