    // Look & Feel
    CONNECT_SETTING(Theme, themeChanged, Value, Values, ThemeVariantValue);
    CONNECT_SETTING(Font, fontChanged, Value);
    CONNECT_SETTING(FontSize, fontSizeChanged, Value);
    CONNECT_SETTING(EmojiFont, emojiFontChanged, Value);
    CONNECT_SETTING(EnableUIAnimations, reducedMotionChanged, Value);
    CONNECT_SETTING(CompactRoomList, compactRoomListChanged, Value);
    CONNECT_SETTING(ShowRoomListTime, showRoomListTimeChanged, Value);
    CONNECT_SETTING(ShowLastMessagePreview, showLastMessagePreviewChanged, Value);
    CONNECT_SETTING(ShowCommunityNotificationCounts, showCommunityNotificationCountsChanged, Value);
    CONNECT_SETTING(UseCircularAvatars, useCircularAvatarsChanged, Value);
    CONNECT_SETTING(UseIdenticon, useIdenticonChanged, Value);
    CONNECT_SETTING(ScrollbarsInRoomlist, scrollbarsInRoomlistChanged, Value);
    CONNECT_SETTING(RoomSorting, roomSortOrderChanged, Value);
    CONNECT_SETTING(ShowCommunitiesSidebar, showCommunitiesSidebarChanged, Value);
    CONNECT_SETTING(MobileMode, mobileModeChanged, Value);
    CONNECT_SETTING(EnableSwipeGestures, enableSwipeGesturesChanged, Value);
