    // Composer
    CONNECT_SETTING_ID(ComposerInputMarkdownEnabled, markdownEnabledChanged, Value);
    CONNECT_SETTING_ID(ComposerInputSendKey, sendMessageKeyChanged, Value);
    CONNECT_SETTING_ID(ComposerInputAutoReplaceEmoji, autoReplaceEmojiChanged, Value);
    CONNECT_SETTING_ID(ComposerTypingSendEnabled, sendTypingNotificationsEnabledChanged, Value);
    CONNECT_SETTING_ID(ComposerExtrasStickersEnabled, stickersEnabledChanged, Value);
