    // Look & Feel
    CONNECT_SETTING_ID(UiThemeSlug, themeChanged, Value, Values, ThemeVariantValue);
    CONNECT_SETTING_ID(UiFontFamily, fontChanged, Value);
    CONNECT_SETTING_ID(UiFontSizePt, fontSizeChanged, Value);
    CONNECT_SETTING_ID(UiFontEmojiFamily, emojiFontChanged, Value);
    CONNECT_SETTING_ID(UiLayoutContentMaxWidthPx, maxContentWidthChanged, Value);
    CONNECT_SETTING_ID(UiMotionAnimationsEnabled, uiMotionAnimationsEnabledChanged, Value);
    CONNECT_SETTING_ID(UiInputMode, uiInputModeTouchEnabledChanged, Value);
    CONNECT_SETTING_ID(SidebarsRoomListCompact, sidebarsRoomListCompactChanged, Value);
    CONNECT_SETTING_ID(
      SidebarsRoomListShowLastMessageTime, sidebarsRoomListShowLastMessageTimeChanged, Value);
    CONNECT_SETTING_ID(SidebarsRoomListLastMessagePreview, sidebarsRoomListLastMessagePreviewChanged, Value);
    CONNECT_SETTING_ID(
      SidebarsRoomListShowCommunityCounts, sidebarsRoomListShowCommunityCountsChanged, Value);
    CONNECT_SETTING_ID(UiAvatarsCircular, circularAvatarsEnabledChanged, Value);
    CONNECT_SETTING_ID(UiAvatarsIdenticonFallback, identiconFallbackEnabledChanged, Value);
    CONNECT_SETTING_ID(
      SidebarsRoomListScrollbarsEnabled, sidebarsRoomListScrollbarsVisibleChanged, Value);
    CONNECT_SETTING_ID(SidebarsRoomListSort, sidebarsRoomListSortChanged, Value);
    CONNECT_SETTING_ID(SidebarsCommunitiesVisible, sidebarsCommunitiesVisibleChanged, Value);
    CONNECT_SETTING_ID(UiInputTouchSwipeGesturesEnabled, uiInputTouchSwipeGesturesEnabledChanged, Value);
