    // Composer
    CONNECT_SETTING(Markdown, markdownChanged, Value);
    CONNECT_SETTING(SendMessageKey, sendMessageKeyChanged, Value);
    CONNECT_SETTING(AutoReplaceEmoji, autoReplaceEmojiChanged, Value);
    CONNECT_SETTING(TypingNotifications, typingNotificationsChanged, Value);
    CONNECT_SETTING(ReadReceipts, readReceiptsChanged, Value);
    CONNECT_SETTING(EnableStickers, enableStickersChanged, Value);
